### ISSUE TITLE
EmailListsController isn't calling the `call` method for AddsUserToList

### ISSUE THREAD

**Issue by aaronmcadam** [orend/register#2]
See https://github.com/orend/register/blob/master/app/controllers/email_lists_controller.rb#L5

**Comment by orend** [comment]
Thanks, but the call is actually happening. When you write `object.()` ruby will call the `call` method on `object`. This syntax is in fact identical to the syntax of calling a proc, so if you want to you can pass a proc instead of a mock object.

**Comment by aaronmcadam** [comment]
@orend Sorry! Good to know, thanks!

**Comment by orend** [comment]
no need to be sorry! you didn't know that you didn't know, so you did the right thing and asked.
